<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <PlatformTarget>x86</PlatformTarget>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>HansLaserDateSerialDemo</RootNamespace>
        <AssemblyName>LaserMarkingApp</AssemblyName>
        <Version>1.0.4</Version>
        <ApplicationIcon>favicon.ico</ApplicationIcon>
        <Platforms>AnyCPU;x86;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <None Update="config.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="favicon.ico">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
</Project>
