//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HansLaserDateSerialDemo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HansLaserDateSerialDemo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Q Exit 的本地化字符串。
        /// </summary>
        public static string action_exit {
            get {
                return ResourceManager.GetString("action_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M Laser Mark 的本地化字符串。
        /// </summary>
        public static string action_mark {
            get {
                return ResourceManager.GetString("action_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P Red Light Preview 的本地化字符串。
        /// </summary>
        public static string action_preview {
            get {
                return ResourceManager.GetString("action_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S Used/Skip 的本地化字符串。
        /// </summary>
        public static string action_skip {
            get {
                return ResourceManager.GetString("action_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The program is already running. A second instance cannot be started. 的本地化字符串。
        /// </summary>
        public static string already_running_message {
            get {
                return ResourceManager.GetString("already_running_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Configuration 的本地化字符串。
        /// </summary>
        public static string app_config {
            get {
                return ResourceManager.GetString("app_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hans Laser Secondary Development Demo 的本地化字符串。
        /// </summary>
        public static string app_demo_title {
            get {
                return ResourceManager.GetString("app_demo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser Marking App 的本地化字符串。
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applying configuration... 的本地化字符串。
        /// </summary>
        public static string applying_config_status {
            get {
                return ResourceManager.GetString("applying_config_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator confirmed the number was already used or should be skipped 的本地化字符串。
        /// </summary>
        public static string audit_skip_confirmed {
            get {
                return ResourceManager.GetString("audit_skip_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Configuration 的本地化字符串。
        /// </summary>
        public static string basic_config {
            get {
                return ResourceManager.GetString("basic_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Device Configuration Directory 的本地化字符串。
        /// </summary>
        public static string browse_device_config_dir {
            get {
                return ResourceManager.GetString("browse_device_config_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system is busy. Please try again later. 的本地化字符串。
        /// </summary>
        public static string busy_retry_message {
            get {
                return ResourceManager.GetString("busy_retry_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load configuration: {0} 的本地化字符串。
        /// </summary>
        public static string config_load_failed_fmt {
            get {
                return ResourceManager.GetString("config_load_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded config.json. Use Settings on the toolbar to modify and apply configuration. 的本地化字符串。
        /// </summary>
        public static string config_loaded_log {
            get {
                return ResourceManager.GetString("config_loaded_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration saved and applied:  的本地化字符串。
        /// </summary>
        public static string config_saved_applied_prefix {
            get {
                return ResourceManager.GetString("config_saved_applied_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete product {0}? 的本地化字符串。
        /// </summary>
        public static string confirm_delete_product_fmt {
            get {
                return ResourceManager.GetString("confirm_delete_product_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm number {0} has been used or must be skipped? 的本地化字符串。
        /// </summary>
        public static string confirm_skip_message_fmt {
            get {
                return ResourceManager.GetString("confirm_skip_message_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Used/Skip 的本地化字符串。
        /// </summary>
        public static string confirm_skip_title {
            get {
                return ResourceManager.GetString("confirm_skip_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created At 的本地化字符串。
        /// </summary>
        public static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current No. 的本地化字符串。
        /// </summary>
        public static string current_num {
            get {
                return ResourceManager.GetString("current_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Part No. 的本地化字符串。
        /// </summary>
        public static string customer_part_number {
            get {
                return ResourceManager.GetString("customer_part_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Configuration Directory 的本地化字符串。
        /// </summary>
        public static string device_config_dir {
            get {
                return ResourceManager.GetString("device_config_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DLL Version 的本地化字符串。
        /// </summary>
        public static string dll_version {
            get {
                return ResourceManager.GetString("dll_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Product 的本地化字符串。
        /// </summary>
        public static string edit_product {
            get {
                return ResourceManager.GetString("edit_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Foot Pedal Trigger 的本地化字符串。
        /// </summary>
        public static string enable_foot_pedal {
            get {
                return ResourceManager.GetString("enable_foot_pedal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter the device configuration directory first 的本地化字符串。
        /// </summary>
        public static string fill_device_config_dir {
            get {
                return ResourceManager.GetString("fill_device_config_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save required product and runtime settings from the toolbar. The app then initializes and loads the product template. 的本地化字符串。
        /// </summary>
        public static string flow_step_config_ready_text {
            get {
                return ResourceManager.GetString("flow_step_config_ready_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Ready 的本地化字符串。
        /// </summary>
        public static string flow_step_config_ready_title {
            get {
                return ResourceManager.GetString("flow_step_config_ready_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S skips an abnormal number. Q exits and keeps the pending number. 的本地化字符串。
        /// </summary>
        public static string flow_step_confirm_exception_text {
            get {
                return ResourceManager.GetString("flow_step_confirm_exception_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Exception 的本地化字符串。
        /// </summary>
        public static string flow_step_confirm_exception_title {
            get {
                return ResourceManager.GetString("flow_step_confirm_exception_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After configuration is loaded, a number is generated from the pattern. Number marking state is managed in the database and can recover after power loss. 的本地化字符串。
        /// </summary>
        public static string flow_step_number_ready_text {
            get {
                return ResourceManager.GetString("flow_step_number_ready_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number Ready 的本地化字符串。
        /// </summary>
        public static string flow_step_number_ready_title {
            get {
                return ResourceManager.GetString("flow_step_number_ready_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P opens red light preview. M starts laser marking from the configuration. 的本地化字符串。
        /// </summary>
        public static string flow_step_preview_mark_text {
            get {
                return ResourceManager.GetString("flow_step_preview_mark_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview/Mark 的本地化字符串。
        /// </summary>
        public static string flow_step_preview_mark_title {
            get {
                return ResourceManager.GetString("flow_step_preview_mark_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foot Pedal Trigger 的本地化字符串。
        /// </summary>
        public static string foot_pedal_trigger {
            get {
                return ResourceManager.GetString("foot_pedal_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generator 的本地化字符串。
        /// </summary>
        public static string generator {
            get {
                return ResourceManager.GetString("generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generator is invalid. 的本地化字符串。
        /// </summary>
        public static string generator_invalid {
            get {
                return ResourceManager.GetString("generator_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking History 的本地化字符串。
        /// </summary>
        public static string history_marking_records {
            get {
                return ResourceManager.GetString("history_marking_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking call failed: {0} 的本地化字符串。
        /// </summary>
        public static string mark_error_fmt {
            get {
                return ResourceManager.GetString("mark_error_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking did not finish normally: {0}. The number remains pending confirmation. 的本地化字符串。
        /// </summary>
        public static string mark_not_normal_fmt {
            get {
                return ResourceManager.GetString("mark_not_normal_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser marking will start immediately. 的本地化字符串。
        /// </summary>
        public static string mark_now {
            get {
                return ResourceManager.GetString("mark_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking finished normally. Number submitted: {0} 的本地化字符串。
        /// </summary>
        public static string mark_success_fmt {
            get {
                return ResourceManager.GetString("mark_success_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Laser marking is waiting. Press the foot pedal or send the trigger signal. 的本地化字符串。
        /// </summary>
        public static string mark_wait_foot {
            get {
                return ResourceManager.GetString("mark_wait_foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marked At 的本地化字符串。
        /// </summary>
        public static string marked_at {
            get {
                return ResourceManager.GetString("marked_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking Template 的本地化字符串。
        /// </summary>
        public static string marking_template {
            get {
                return ResourceManager.GetString("marking_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Product 的本地化字符串。
        /// </summary>
        public static string new_product {
            get {
                return ResourceManager.GetString("new_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not read 的本地化字符串。
        /// </summary>
        public static string not_read {
            get {
                return ResourceManager.GetString("not_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No. 的本地化字符串。
        /// </summary>
        public static string num {
            get {
                return ResourceManager.GetString("num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps 的本地化字符串。
        /// </summary>
        public static string op_flow {
            get {
                return ResourceManager.GetString("op_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Setting 的本地化字符串。
        /// </summary>
        public static string open_seetting {
            get {
                return ResourceManager.GetString("open_seetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed: {0} 的本地化字符串。
        /// </summary>
        public static string operation_failed_fmt {
            get {
                return ResourceManager.GetString("operation_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern cannot be empty. 的本地化字符串。
        /// </summary>
        public static string pattern_required {
            get {
                return ResourceManager.GetString("pattern_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New number is reserved. Waiting for preview, marking, or skip confirmation. 的本地化字符串。
        /// </summary>
        public static string pending_new_message {
            get {
                return ResourceManager.GetString("pending_new_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous number was not confirmed. Check the workpiece/MES before reprinting or skipping. 的本地化字符串。
        /// </summary>
        public static string pending_previous_message {
            get {
                return ResourceManager.GetString("pending_previous_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red light preview in progress... 的本地化字符串。
        /// </summary>
        public static string preview_busy {
            get {
                return ResourceManager.GetString("preview_busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red light preview finished: {0} 的本地化字符串。
        /// </summary>
        public static string preview_done_fmt {
            get {
                return ResourceManager.GetString("preview_done_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red light preview failed: {0} 的本地化字符串。
        /// </summary>
        public static string preview_failed_fmt {
            get {
                return ResourceManager.GetString("preview_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Configuration 的本地化字符串。
        /// </summary>
        public static string prod_config {
            get {
                return ResourceManager.GetString("prod_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product 的本地化字符串。
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string product_name_required {
            get {
                return ResourceManager.GetString("product_name_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save product: {0} 的本地化字符串。
        /// </summary>
        public static string product_save_failed_fmt {
            get {
                return ResourceManager.GetString("product_save_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product saved. 的本地化字符串。
        /// </summary>
        public static string product_saved_message {
            get {
                return ResourceManager.GetString("product_saved_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product settings are invalid: {0} 的本地化字符串。
        /// </summary>
        public static string product_settings_invalid_fmt {
            get {
                return ResourceManager.GetString("product_settings_invalid_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product is missing a marking template. 的本地化字符串。
        /// </summary>
        public static string product_template_missing {
            get {
                return ResourceManager.GetString("product_template_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product marking template was not found. 的本地化字符串。
        /// </summary>
        public static string product_template_not_found {
            get {
                return ResourceManager.GetString("product_template_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marking template cannot be empty. 的本地化字符串。
        /// </summary>
        public static string product_template_required {
            get {
                return ResourceManager.GetString("product_template_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read failed: HansAdvInterface.dll was not found under MachinePath 的本地化字符串。
        /// </summary>
        public static string read_failed_dll_missing {
            get {
                return ResourceManager.GetString("read_failed_dll_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read failed: {0} 的本地化字符串。
        /// </summary>
        public static string read_failed_fmt {
            get {
                return ResourceManager.GetString("read_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read Version 的本地化字符串。
        /// </summary>
        public static string read_version {
            get {
                return ResourceManager.GetString("read_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reapplying configuration. Previous device session has been closed. 的本地化字符串。
        /// </summary>
        public static string reapplying_config_message {
            get {
                return ResourceManager.GetString("reapplying_config_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string remark {
            get {
                return ResourceManager.GetString("remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reprint 的本地化字符串。
        /// </summary>
        public static string reprint {
            get {
                return ResourceManager.GetString("reprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reprinting historical number... 的本地化字符串。
        /// </summary>
        public static string reprint_busy {
            get {
                return ResourceManager.GetString("reprint_busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reprint historical number {0}? 的本地化字符串。
        /// </summary>
        public static string reprint_confirm_fmt {
            get {
                return ResourceManager.GetString("reprint_confirm_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical number reprint failed: {0} 的本地化字符串。
        /// </summary>
        public static string reprint_error_fmt {
            get {
                return ResourceManager.GetString("reprint_error_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please start the product configuration and template before reprinting. 的本地化字符串。
        /// </summary>
        public static string reprint_missing_current_msg {
            get {
                return ResourceManager.GetString("reprint_missing_current_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical number reprint did not finish normally: {0} 的本地化字符串。
        /// </summary>
        public static string reprint_not_normal_fmt {
            get {
                return ResourceManager.GetString("reprint_not_normal_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical number reprinted 的本地化字符串。
        /// </summary>
        public static string reprint_remark {
            get {
                return ResourceManager.GetString("reprint_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical number reprinted: {0} 的本地化字符串。
        /// </summary>
        public static string reprint_success_fmt {
            get {
                return ResourceManager.GetString("reprint_success_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Historical Reprint 的本地化字符串。
        /// </summary>
        public static string reprint_title {
            get {
                return ResourceManager.GetString("reprint_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please start the configuration and template for the product that owns this historical record before reprinting. 的本地化字符串。
        /// </summary>
        public static string reprint_wrong_product_msg {
            get {
                return ResourceManager.GetString("reprint_wrong_product_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to prepare current number: {0} 的本地化字符串。
        /// </summary>
        public static string reserve_failed_fmt {
            get {
                return ResourceManager.GetString("reserve_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Log 的本地化字符串。
        /// </summary>
        public static string run_log {
            get {
                return ResourceManager.GetString("run_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load saved configuration: {0} 的本地化字符串。
        /// </summary>
        public static string saved_config_load_failed_fmt {
            get {
                return ResourceManager.GetString("saved_config_load_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started with saved configuration:  的本地化字符串。
        /// </summary>
        public static string saved_config_started_prefix {
            get {
                return ResourceManager.GetString("saved_config_started_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seconds 的本地化字符串。
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Marking Template 的本地化字符串。
        /// </summary>
        public static string select_marking_template {
            get {
                return ResourceManager.GetString("select_marking_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Product 的本地化字符串。
        /// </summary>
        public static string select_product {
            get {
                return ResourceManager.GetString("select_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a product in Settings first. 的本地化字符串。
        /// </summary>
        public static string select_product_required {
            get {
                return ResourceManager.GetString("select_product_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial No. 的本地化字符串。
        /// </summary>
        public static string serial_num {
            get {
                return ResourceManager.GetString("serial_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Start 的本地化字符串。
        /// </summary>
        public static string serial_start {
            get {
                return ResourceManager.GetString("serial_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial start must be between 1 and 9999. 的本地化字符串。
        /// </summary>
        public static string serial_start_range {
            get {
                return ResourceManager.GetString("serial_start_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings are invalid: {0} 的本地化字符串。
        /// </summary>
        public static string settings_invalid_fmt {
            get {
                return ResourceManager.GetString("settings_invalid_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmed number used/skipped: {0} 的本地化字符串。
        /// </summary>
        public static string skip_confirmed_log_fmt {
            get {
                return ResourceManager.GetString("skip_confirmed_log_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup failed: {0} 的本地化字符串。
        /// </summary>
        public static string startup_failed_fmt {
            get {
                return ResourceManager.GetString("startup_failed_fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Startup 的本地化字符串。
        /// </summary>
        public static string startup_title {
            get {
                return ResourceManager.GetString("startup_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for service and configuration loaded 的本地化字符串。
        /// </summary>
        public static string state_init_message {
            get {
                return ResourceManager.GetString("state_init_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template 的本地化字符串。
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string timeout {
            get {
                return ResourceManager.GetString("timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Text Alias 的本地化字符串。
        /// </summary>
        public static string variable_text_alias {
            get {
                return ResourceManager.GetString("variable_text_alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View the records 的本地化字符串。
        /// </summary>
        public static string view_record {
            get {
                return ResourceManager.GetString("view_record", resourceCulture);
            }
        }
    }
}
